spring:
  application:
    name: sunsign-cache-app
  cache:
    type: redis
  data:
    redis:
      host: REDIS_HOST # Change this for your implementation
      port: 6379
      password: REDIS_PASSWORD # Change this for your implementation
      timeout: 2000
app:
  zodiac:
    name: Sun Sign App
    version: V1
    message: This message is from application.yml file
    client:
      name: zodiac-client
      url: http://zodiac-svc:8080
      #url: http://localhost:30080
server:
  address: 0.0.0.0
  port: 8081
logging:
  level:
    root: INFO
    logging:
      level:
        org.springframework.data.redis: DEBUG
