apiVersion: v1
kind: Service
metadata:
  name: zodiac-svc
  labels:
    app: zodiac-app
spec:
  type: NodePort
  selector:
    app: zodiac-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080