apiVersion: v1
kind: Service
metadata:
  name: hazelcast-svc
spec:
  ports:
    - port: 5701
      targetPort: 5701
  selector:
    app: hazelcast
  clusterIP: None  # For headless service to support Hazelcast discovery
