apiVersion: v1
kind: Service
metadata:
  name: sunsign-svc
  labels:
    app: sunsign-app
spec:
  type: NodePort
  selector:
    app: sunsign-app
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      nodePort: 30081